apiVersion: batch/v1
kind: Job
metadata:
  name: dispatcher
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: node1-control
      containers:
        - name: dispatcher
          image: williamsdock/mini-dc-dispatcher:v7
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT_NUM
              value: "6379"
            - name: ROUTING_POLICY
              value: "round_robin"
            - name: QUEUE_NODE2
              value: "jobs-node2"
            - name: QUEUE_NODE3
              value: "jobs-node3"
            - name: BUSY_KEY_NODE2
              value: "busy-node2"
            - name: BUSY_KEY_NODE3
              value: "busy-node3"
