apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-node2
  template:
    metadata:
      labels:
        app: worker-node2
    spec:
      nodeSelector:
        kubernetes.io/hostname: node2-worker
      containers:
        - name: worker
          image: williamsdock/mini-dc-worker:v13
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT_NUM
              value: "6379"
            - name: QUEUE_NAME
              value: "jobs-node2"
            - name: WORKER_NAME
              value: "node2-worker"
            - name: BUSY_KEY
              value: "busy-node2"
            - name: TEMP_KEY
              value: "cpu-temp-node2-worker"
            - name: CPU_TEMP_PROM_FILE
              value: "/host/node_exporter_textfile/mini_dc_cpu_temp.prom"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RESULTS_PATH
              value: "/data/job_results.csv"
            - name: METRICS_PORT
              value: "8002"
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_BUCKET
              value: "mini-dc-artifacts"
            - name: MINIO_SECURE
              value: "false"
          ports:
            - name: metrics
              containerPort: 8002
              protocol: TCP
          volumeMounts:
            - name: job-logs
              mountPath: /data
            - name: node-exporter-textfile
              mountPath: /host/node_exporter_textfile
              readOnly: true
      volumes:
        - name: job-logs
          hostPath:
            path: /tmp/mini-dc-logs
            type: DirectoryOrCreate
        - name: node-exporter-textfile
          hostPath:
            path: /var/lib/node_exporter/textfile_collector
            type: DirectoryOrCreate
