apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-node3
  template:
    metadata:
      labels:
        app: worker-node3
    spec:
      nodeSelector:
        kubernetes.io/hostname: node3-worker
      containers:
        - name: worker
          image: williamsdock/mini-dc-worker:v10
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT_NUM
              value: "6379"
            - name: QUEUE_NAME
              value: "jobs-node3"
            - name: WORKER_NAME
              value: "node3-worker"
            - name: BUSY_KEY
              value: "busy-node3"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RESULTS_PATH
              value: "/data/job_results.csv"
            - name: METRICS_PORT
              value: "8002"
          ports:
            - name: metrics
              containerPort: 8002
              protocol: TCP
          volumeMounts:
            - name: job-logs
              mountPath: /data
      volumes:
        - name: job-logs
          hostPath:
            path: /tmp/mini-dc-logs
            type: DirectoryOrCreate
